&[
    "sapi_module_struct", "sapi_headers_struct", "sapi_header_struct", "sapi_request_info",
    "sapi_globals_struct", "zend_executor_globals", "php_core_globals", "zend_compiler_globals",
    "zend_file_handle", "zend_module_entry", "zend_string", "zval", "HashTable", "zend_long",
    "zend_fcall_info", "zend_fcall_info_cache",
    "sapi_startup", "sapi_shutdown", "php_module_startup", "php_module_shutdown", "php_request_startup",
    "php_execute_script", "zend_error", "zend_stream_init_filename", "zend_destroy_file_handle",
    "rapira_get_mode", "rapira_getcwd", "rapira_chdir", "RAPIRA_MODE_CLASSIC", "RAPIRA_MODE_WORKER",
    "RAPIRA_MODE_DISPATCHER", "RAPIRA_OK", "RAPIRA_BAILOUT", "RAPIRA_THROW",
    "RAPIRA_HANDLE_STOP", "RAPIRA_HANDLE_CONTINUE", "RAPIRA_HANDLE_RECYCLE",
    // The linked PHP version and the header version.
    "PHP_VERSION_ID", "php_version_id", "php_version", "rapira_headers_php_version_id",
    "php_tsrm_startup_ex", "ts_resource_ex", "ts_free_thread", "tsrm_shutdown",
    "rapira_tsrmls_cache_update", "rapira_thread_init", "rapira_thread_disarm", "rapira_timer_rearm",
    "rapira_zend_string_init_interned",
    // The embedded-object layout is in rapira_sapi.h.
    "rapira_dispatcher_info_obj",
    // Class entries set during MINIT.
    "rapira_ce_tls", "rapira_ce_inet_address",
    "rapira_ce_unix_address", "rapira_ce_already_finalized_error",
    "rapira_ce_timeout_exception", "rapira_ce_closed_exception",
    "rapira_ce_no_dispatcher_error",
    "zend_argument_value_error", "zend_argument_type_error",
    "rapira_ce_work_discarded_exception",
    // The array walk uses the exported position API.
    "zend_hash_internal_pointer_reset_ex", "zend_hash_get_current_key_ex",
    "zend_hash_get_current_data_ex", "zend_hash_move_forward_ex", "HashPosition",
    "IS_NULL", "IS_ARRAY", "IS_REFERENCE",
    "zend_throw_error", "zend_value_error", "zend_type_error", "zend_throw_exception",
    "zend_update_property_str", "instanceof_function_slow", "zend_zval_value_name", "IS_OBJECT",
    "zend_read_property", "zend_get_exception_base", "zend_ce_throwable", "php_json_encode",
    "smart_str", "PHP_JSON_PARTIAL_OUTPUT_ON_ERROR",
    "add_assoc_stringl_ex", "zend_hash_index_update", "rapira_smart_str_free",
    "object_init_ex", "zend_update_property", "zend_update_property_stringl",
    "zend_update_property_long", "zend_update_property_double", "zend_update_property_null",
    "rapira_array_init", "rapira_symtable_str_find", "rapira_array_is_list", "rapira_zval_enum_case",
    "zend_hash_str_find",
    "rapira_register_known_stringl", "zend_hash_extend", "php_import_environment_variables",
    "zend_is_auto_global_str",
    "zend_property_info", "rapira_zval_stringl", "IS_LONG", "IS_DOUBLE", "IS_PROP_UNINIT", "IS_PROP_REINITABLE",
    "add_assoc_zval_ex", "add_next_index_stringl", "add_next_index_object", "zval_add_ref",
    "zend_object", "zend_class_entry", "zval_ptr_dtor",
    "zend_hash_str_update", "zend_string_init_interned",
    "php_default_post_reader", "php_default_treat_data", "php_default_input_filter", "php_handle_auth_data",
    "SAPI_HEADER_SENT_SUCCESSFULLY", "SAPI_HEADER_SEND_FAILED", "IS_UNDEF", "IS_STRING",
    "E_WARNING", "E_CORE_WARNING", "E_COMPILE_WARNING", "E_USER_WARNING",
    "E_NOTICE", "E_USER_NOTICE", "E_DEPRECATED", "E_USER_DEPRECATED", "E_CORE", "E_FATAL_ERRORS",
]
