[package]
name = "php_sys"
version = "0.1.0"
edition = "2024"
build = "build.rs"
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
log = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["sync"] }
bytes = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
bindgen = "0"
cc = "1.2"

[features]
default = []

